# Generated by Django 5.2.7 on 2025-10-28 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expert_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
